Repository liminalminds/karo, pull requests merged in 2024-04, with the labels that each got.

#18 UI Redesign
  frontend/app/_components/Header.tsx
  frontend/app/_components/Main.tsx
  frontend/app/_components/actions/Action.tsx
  frontend/app/_components/actions/ActionBar.tsx
  frontend/app/_components/actions/ActionList.tsx
  frontend/app/_components/buttons/Close.tsx
  frontend/app/_components/goals/Goal.tsx
  frontend/app/_components/goals/GoalList.tsx
  frontend/app/_components/input/InputAction.tsx
  frontend/app/_components/input/InputTopic.tsx
  frontend/app/_components/menu/Export.tsx
  frontend/app/_components/menu/Import.tsx
  frontend/app/_components/menu/Info.tsx
  frontend/app/_components/menu/Menu.tsx
  frontend/app/_components/modals/About.tsx
  frontend/app/_components/modals/Edit.tsx
  frontend/app/_components/toast.tsx
  frontend/app/_components/topics/Topic.tsx
  frontend/app/_components/topics/TopicBar.tsx
  frontend/app/_components/topics/TopicList.tsx
  frontend/app/_store.ts
  frontend/app/_styles/globals.css
  frontend/app/_types.tsx
  frontend/app/_utils.tsx
  frontend/app/favicon.ico
  frontend/app/global.css
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/background.jpg
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: Feature

#23 Fix: Removes version from metadata title
  frontend/app/layout.tsx
Labels: Bug

#28 Feat: Basic Settings
  .gitignore
  README.md
  frontend/app/global.css
  frontend/app/icon.ico
  frontend/app/layout.tsx
  frontend/app/page.tsx
Labels: Bug, Feature

#25 feat: Adds strike-through animation for the completed tasks
  frontend/app/global.css
Labels: Feature, Good First Issue

#34 Feat: Delete Icon Appears
  frontend/app/global.css
Labels: Feature

#39 SSC, Zustand & Local Storage
  README.md
  frontend/.eslintrc.json
  frontend/app/components/Header.tsx
  frontend/app/components/InputNew.tsx
  frontend/app/components/Main.tsx
  frontend/app/components/MiniReport.tsx
  frontend/app/components/Settings.tsx
  frontend/app/components/Task.tsx
  frontend/app/components/TaskList.tsx
  frontend/app/components/Toast.tsx
  frontend/app/global.css
  frontend/app/icon.ico
  frontend/app/interfaces/options.ts
  frontend/app/interfaces/props.ts
  frontend/app/interfaces/quest.ts
  frontend/app/interfaces/store.ts
  frontend/app/interfaces/task.ts
  frontend/app/layout.tsx
  frontend/app/not-found.tsx
  frontend/app/page.tsx
  frontend/app/store/store.ts
  frontend/app/styles/Header.module.css
  frontend/app/styles/InputNew.module.css
  frontend/app/styles/MiniReport.module.css
  frontend/app/styles/NotFound.module.css
  frontend/app/styles/Settings.module.css
  frontend/app/styles/Task.module.css
  frontend/app/styles/global.css
  frontend/app/utils/constants.ts
  frontend/app/utils/idgen.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
Labels: Feature, Refactor
